version: "3.8"
services:

    php:
        build:
            context: ./docker/php/
            dockerfile: Dockerfile
        container_name: PHP7        
        environment:
#          - APP_ENV=dev
#          - APP_DEBUG=0
#          - APP_SECRET=EDITME
          - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_DATABASE}?serverVersion=8
#          - MAILER_URL=smtp://localhost
#          - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
        volumes:
            - ./app:/var/www/app            
        working_dir: /var/www/app
            
    web:
        image: nginx:1.19.1
        container_name: Nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./app/public:/var/www/app/public
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/logs:/var/log/nginx/
        links:
            - php

    mysql:
        image: mysql:8
        container_name: ${MYSQL_HOST}
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          
        volumes:
          - ./docker/mysql/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
        ports:
            - 3306:3306
            
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
            
#    composer:
#        image: composer:1
#        container_name: Composer
#        command: install
##        command: update
#        environment:
#          - MYSQL_HOST=${MYSQL_HOST}
#          - MYSQL_DATABASE=${MYSQL_DATABASE}
#          - MYSQL_USER=${MYSQL_USER}
#          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#        volumes:
#            - ./app:/app/
#            - ~/.ssh:/root/.ssh