version: "3.8"
services:

    php:
        build:
            context: ./docker/php/
            dockerfile: Dockerfile
        container_name: PHP7
#        ports:
#            - "9000:9000"
        environment:
          - APP_ENV=dev
          - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_DATABASE}?serverVersion=8
        volumes:
            - ./app:/var/www/app            
        working_dir: /var/www/app
        
#    encore:
#        image: node:10-alpine
#        volumes:
#            - ./app:/var/www/app
#        ports:
#            - "8080:8080"
#        working_dir: /var/www/app
#        command: ["yarn", "dev-server", "--host=0.0.0.0"]
#            
    node:
        image: node:14.8
        container_name: Node
        command: yarn install
#        command: yarn encore dev --watch            
        working_dir: /var/www/app
        volumes:
            - ./app:/var/www/app  
#    encore:
#        image: node:14.8
#        container_name: encore
#        command: yarn install
##        command: yarn encore dev --watch   
##        command: ["yarn", "dev-server", "--host=0.0.0.0"]
#        working_dir: /var/www/app
#        volumes:
#            - ./app:/var/www/app  
    web:
        image: nginx:1.19.1
        container_name: Nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./app/public:/var/www/app/public
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/logs:/var/log/nginx/
        links:
            - php

    mysql:
        image: mysql:8
        container_name: ${MYSQL_HOST}
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          
#        volumes:
#          - ./docker/mysql/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
        ports:
            - 3306:3306
            
#    adminer:
#        image: adminer
#        restart: always
#        container_name: Adminer
#        ports:
#            - 8080:8080
            
#    composer:
#        image: composer:1
#        container_name: Composer
#        command: install
##        command: update
#        environment:
#          - MYSQL_HOST=${MYSQL_HOST}
#          - MYSQL_DATABASE=${MYSQL_DATABASE}
#          - MYSQL_USER=${MYSQL_USER}
#          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#        volumes:
#            - ./app:/app/
#            - ~/.ssh:/root/.ssh

#    node:
#        image: node:14.8
#        container_name: Node
##        command: yarn install
#        command: yarn encore dev --watch            
#        working_dir: /var/www/app
#        volumes:
#            - ./app:/var/www/app  